# -*- coding: utf-8 -*-
"""Exercicio 17

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15EoG9vApgKn4a5dpq7RIFmREYT2CbYUJ
"""

### Exercicio 17 - Crie uma função que retorne uma lista com valor padrão. Para esta função, consideraremos como argumentos de entrada a quantidade de
# elementos e o valor padrão a ser atribuído a todos eles. Exemplo de retorno: [1,1,1,1,1,1,1,1] [“A”,”A”,”A”,”A”]

def funcao17(quant,valor):
  lista = []
  for i in range(quant):
    lista.append(valor)
  return lista

resultado = funcao17(4,"A") ### <- inserir a quantidade e valor da lista aqui
print(resultado)