# -*- coding: utf-8 -*-
"""Exercicio 13

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15EoG9vApgKn4a5dpq7RIFmREYT2CbYUJ
"""

### Exercicio 13 - duplicou o 12