# -*- coding: utf-8 -*-
"""Exercicio 19

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15EoG9vApgKn4a5dpq7RIFmREYT2CbYUJ
"""

### Exercicio 19 - Elabore uma função que receba a distância em Km e a quantidade de litros de gasolina consumidos por um carro em um percurso, calcule
# o consumo em Km/l e escreva uma mensagem de acordo com a tabela abaixo:

def funcao19(distancia,litros):
  kmL = distancia / litros
  if kmL < 8:
    print("Gasta muito!")
  elif kmL >= 8 and kmL <= 15:
    print("Econômico!")
  else:
    print("Super econômico")


distancia = float(input("Digite a distancia: "))
litros = float(input("Digite a quantidade de litros: "))

resultado = funcao19(distancia,litros)