# -*- coding: utf-8 -*-
"""Exercicio 20

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15EoG9vApgKn4a5dpq7RIFmREYT2CbYUJ
"""

### Exercicio 20 - Escreva uma função que receba como parâmetro a quantidade de alunos para apresentar um trabalho. Esta função deve solicitar ao usuário
# os nomes de alunos de uma sala de aula. Após cadastrar a quantidade informada de alunos a função deve sortear e retornar para o usuário o aluno(a) que
#irá apresentar o trabalho primeiro.

import random

def funcao20(quant):
  lista = []
  for i in range(quant):
    nomes = str(input("Digite um nome: "))
    lista.append(nomes)
  aluno_sorteado = random.choice(lista)
  print("O primeiro aluno(a) a apresentar será:",aluno_sorteado)


funcao20(3) ### <- inserir a quantidade de alunos aqui