# -*- coding: utf-8 -*-
"""Exercicio 8

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15EoG9vApgKn4a5dpq7RIFmREYT2CbYUJ
"""

### Exercicio 8 - Crie uma função que receba a altura e o raio de um cilindro circular e retorne o volume do cilindro. O volume de um cilindro circular e
# calculado por meio da seguinte fórmula: V = π * raio2 * altura, onde π = 3.141592.


def funcao8(alt,raio):
  V = 3.141592 * (raio **2 ) * alt
  return V

alt = float(input("Digite a altura: "))
raio = float(input("Digite o raio: "))

resultado = funcao8(alt,raio)

print(resultado)