# -*- coding: utf-8 -*-
"""Exercicio 15

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15EoG9vApgKn4a5dpq7RIFmREYT2CbYUJ
"""

### Exercicio 15 - Crie uma função que receba uma lista como argumento, os valores da lista devem ser numéricos, por fim retorne a média desses valores.

def funcao15(lista):
  media = sum(lista) / len(lista)
  return media

lista = [23,47,12,2] ### <- inserir os numeros da lista aqui

resultado = funcao15(lista)
print(resultado)