# -*- coding: utf-8 -*-
"""Exercicio 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15EoG9vApgKn4a5dpq7RIFmREYT2CbYUJ
"""

### Exercicio 1 - Crie uma função que receba dois números como parâmetros e mostre a potência do número elevado a n vezes.

def funcao1(num,pot):
  poten = num ** pot
  print ("O resultado é:", poten)

num = int(input("Digite o numero: "))
pot = int(input("Digite a potencia: "))

funcao1(num,pot)