# -*- coding: utf-8 -*-
"""Exercicio 16

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15EoG9vApgKn4a5dpq7RIFmREYT2CbYUJ
"""

### Exercicio 16 - Crie uma função que receba como argumento a potência elétrica de determinado aparelho e o tempo ligado e retorne o consumo em KWh em
# seguida chame outra função para calcular a conta de energia, levando em consideração o consumo e o valor do KWh como argumentos.

def funcao16(potencia,tempo):
  consumo = (potencia * tempo)/1000
  return consumo

def funcao_conta(consumo,valor):
  conta = consumo * valor
  return conta

potencia = float(input("Digite a potencia: "))
tempo = int(input("Digite o tempo em horas: "))
valor = float(input("Digite o valor por hora: "))

resultado1 = funcao16(potencia,tempo)
print(resultado1)

resultado2 = funcao_conta(resultado1,valor)
print(resultado2)