# -*- coding: utf-8 -*-
"""Exercicio 3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15EoG9vApgKn4a5dpq7RIFmREYT2CbYUJ
"""

### Exercicio 3 - Faça uma função que receba 3 números inteiros como parâmetro, representando horas, minutos e segundos, e os converta em segundos.

def funcao3(horas,min,seg):
  hor = horas * 3600
  min = min * 60
  seg = seg * 1
  return hor + min + seg


horas = int(input("Digite as horas: "))
min = int(input("Digite os minutos: "))
seg = int(input("Digite os segundos: "))

SegTotal = funcao3(horas,min,seg)

print(SegTotal)