# -*- coding: utf-8 -*-
"""Exercicio 5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15EoG9vApgKn4a5dpq7RIFmREYT2CbYUJ
"""

### Exercicio 5 - Reverso do número. Faça uma função que retorne o reverso de um número inteiro informado. Por exemplo: 127 -> 721.

def funcao5(num):
  num_str = str(num)
  num_invertido_str = num_str[::-1]
  num_invertido = int(num_invertido_str)
  return num_invertido

resultado = funcao5(65694612)  # <- inserir os numeros dentro dos parenteses
print(resultado)