# -*- coding: utf-8 -*-
"""Exercicio 11

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15EoG9vApgKn4a5dpq7RIFmREYT2CbYUJ
"""

### Exercicio 11 - Crie uma função que efetue o cálculo do salário e como retorno teremos o valor a ser pago conforme o número de horas trabalhadas.
# Considere a carga horária de 40h por semana como salário base, caso ultrapasse o limite de 40h, o funcionário deve receber 50% a mais por hora excedente.

def funcao11(valor,horas):
  if horas > 40:
    horas_extras = (horas - 40) * (valor * 1.5)
    salario = (valor * 40) + horas_extras
  else:
    salario = valor * horas
  return salario


valor = float(input("Digite o valor da hora: "))
horas = int(input("Digite a quantidade de horas: "))

salario_total = funcao11(valor,horas)
print(salario_total)