# -*- coding: utf-8 -*-
"""Exercicio 9

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15EoG9vApgKn4a5dpq7RIFmREYT2CbYUJ
"""

### Exercicio 9 - Elabore uma função que receba três notas de um aluno como parâmetros e uma letra. Se a letra for A, a função deverá calcular a média
# aritmética das notas do aluno; se for P, deverá calcular a média ponderada, com pesos 5, 3 e 2.

def funcao9(nota1,nota2,nota3,letra):
  if letra == "A":
    media = (nota1 + nota2 + nota3)/3
  elif letra == "P":
    media = ((nota1 * 5) + (nota2 * 3) + (nota3 * 2)) / 10
  print(media)


nota1 = float(input("Digite a nota 1: "))
nota2 = float(input("Digite a nota 2: "))
nota3 = float(input("Digite a nota 3: "))
letra = str(input("Digite a letra: "))

resultado = funcao9(nota1,nota2,nota3,letra)