# -*- coding: utf-8 -*-
"""Exercicio 7

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15EoG9vApgKn4a5dpq7RIFmREYT2CbYUJ
"""

### Exercicio 7 - Crie uma função que receba uma temperatura em graus Celsius e retorne-a convertida em graus Fahrenheit.
# A fórmula de conversão é: F = C ∗ (9.0/5.0) + 32.0, sendo F a temperatura em Fahrenheit e C a temperatura em Celsius.

def funcao7(temp_C):
  F = temp_C * (9.0/5.0) + 32.0
  return F

temp_C = float(input("Digite a temperatura em Celsius: "))

temperatura_Fahrenheit = funcao7(temp_C)
print(temperatura_Fahrenheit)