# -*- coding: utf-8 -*-
"""Exercicio 10

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15EoG9vApgKn4a5dpq7RIFmREYT2CbYUJ
"""

### Exercicio 10 - Elabore uma função que receba dois valores numéricos e um símbolo. Este símbolo representara a operação que se deseja efetuar com
# os números. Se o símbolo for + deverá ser realizada uma adição, se for − uma subtração, se for / uma divisão e se for ∗ será efetuada uma multiplicação.

def funcao10(num1,num2,simb):
  if simb == "+":
    operacao = num1 + num2
  elif simb == "-":
    operacao = num1 - num2
  elif simb == "/":
    operacao = num1 / num2
  elif simb == "*":
    operacao = num1 * num2
  return operacao

num1 = float(input("Digite o primeiro numero: "))
num2 = float(input("Digite o segundo numero: "))
simb = str(input("Digite o simbolo da operação: "))

resultado = funcao10(num1,num2,simb)
print(resultado)