# -*- coding: utf-8 -*-
"""Exercicio 14

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15EoG9vApgKn4a5dpq7RIFmREYT2CbYUJ
"""

### Exercicio 14 - Elabore uma função que receba por parâmetro dois valores X e Z. Calcule e retorne o resultado de X^Z para o programa principal.
# Atenção não utilize nenhuma função pronta de exponenciação.

def funcao14(x,z):
   resultado = 1
   while z > 0:
    resultado = resultado * x
    z = z - 1
   return resultado

x = int(input("Digite o numero: "))
z = int(input("Digite a potencia: "))

resultado = funcao14(x,z)
print(resultado)