# -*- coding: utf-8 -*-
"""Exercicio 4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15EoG9vApgKn4a5dpq7RIFmREYT2CbYUJ
"""

### Exercicio 4 - Elaborar uma função para retornar o maior de três números recebidos por parâmetro.

def funcao4(num1,num2,num3):
  if num1 > num2 and num1 > num3:
    return num1
  elif num2 > num1 and num2 > num3:
    return num2
  elif num3 > num1 and num3 > num2:
    return num3

resultado = funcao4(23,49,880) # <- inserir os numeros dentro dos parenteses
print(resultado)