# -*- coding: utf-8 -*-
"""Exercicio 18

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15EoG9vApgKn4a5dpq7RIFmREYT2CbYUJ
"""

### Exercicio 18 - Crie uma função que receba como argumento uma lista, com valores de qualquer tipo. A função deve imprimir todos os elementos da lista
# numerando-os. Exemplo:
# 1, Pera
# 2, Uva
# 3, Maça
# 4, Salada mista

def funcao18(lista):
  for indice in range(len(lista)):
      print(f"{indice + 1} - {lista[indice]}")

lista = ["Pera","Uva","Maça","Salada Mista",] ### <- inserir os valores da lista aqui

funcao18(lista)