# -*- coding: utf-8 -*-
"""Exercicio 12

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15EoG9vApgKn4a5dpq7RIFmREYT2CbYUJ
"""

### Exercicio 12 - O gestor de uma rede de shoppings, precisa contratar um sistema para administrar o estacionamento, a principal função do sistema é
# calcularTempo(). Considere o valor mínimo de R$9,00 por hora e R$ 1,50 por hora adicional. O principal argumento da função é o tempo utilizado em
# minutos, a função deve retornar o valor total. Caso o usuário fique no estacionamento por menos de 15 minutos, o tempo utilizado não será cobrado.

def funcao12(tempo):
  if tempo < 15:
    valor = "Não cobrado"
  elif tempo >= 15 and tempo <= 60:
    valor = "9.00"
  else:
    horas_adicionais = (tempo - 60) // 60
    minutos_restantes = (tempo - 60) % 60
    if minutos_restantes > 0:
      horas_adicionais += 1
    valor = 9.00 + (horas_adicionais * 1.50)
  return valor


tempo = int(input("Digite os minutos: "))

resultado = funcao12(tempo)
print(resultado)