# -*- coding: utf-8 -*-
"""Exercicio 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15EoG9vApgKn4a5dpq7RIFmREYT2CbYUJ
"""

### Exercicio 2 - Faça uma função para verificar se um número é positivo ou negativo. Sendo que o valor de retorno será 1 se positivo,
# -1 se negativo e 0 se for igual a 0.

def funcao2(num):
  if num == 0:
    return "0"
  elif num >= 1:
    return "Positivo"
  else:
    return "Negativo"

num = float(input("Digite o numero: "))

resultado = funcao2(num)

print(resultado)


# Não entendi se era pra retornar as palavras ou os numeros

def funcao2(num):
  if num == 0:
    return "0"
  elif num >= 1:
    return "1"
  else:
    return "-1"

num = float(input("Digite o numero: "))

resultado = funcao2(num)

print(resultado)