# -*- coding: utf-8 -*-
"""Exercicio 6

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15EoG9vApgKn4a5dpq7RIFmREYT2CbYUJ
"""

### Exercicio 6 - Crie uma função de um programa de teste para o cálculo do volume de uma esfera. Sendo que o raio é passado por parâmetro? V = 4/3 ∗ π ∗ R3

def funcao6(raio):
  V = 4/3 * 3.141592 * (raio ** 3)
  print(V)

funcao6(8) # <- inserir o valor de raio dentro dos parenteses